name: Release

on:
    push:
        branches:
            - action_test

jobs:

    compile:
        name: Compile
        runs-on: ubuntu-16.04
        steps:
            - name: Install deps
              run: |
                sudo apt-get install libboost-log-dev libboost-program-options-dev libusb-1.0-0-dev build-essential

            - name: Setup dirs
              run: |
                mkdir -p ~/src/Hauppauge
                cd ~/src/Hauppauge

#            - name: Download Hauppauge source
#              run: |
#                mkdir -p ~/src/Hauppauge
#                cd ~/src/Hauppauge
#                curl -O https://s3.amazonaws.com/hauppauge/linux/hauppauge_hdpvr2_157321_patched_2016-09-26.tar.gz
#                tar -xzf hauppauge_hdpvr2_157321_patched_2016-09-26.tar.gz

            - name: Checkout
              uses: actions/checkout@v2

# pwd after checkoout: /home/runner/work/HauppaugeUSB/HauppaugeUSB

            - name: Testing
              run: |
                pwd
                ls
    

