name: Release

on:
    push:
        branches:
            - action_test

jobs:

    compile:
        name: Compile
        runs-on: ubuntu-16.04
        steps:
            - name: Install deps
#              run: |
#                pwd
#                sudo apt-get install libboost-log-dev libboost-program-options-dev libusb-1.0-0-dev build-essential

            - name: Setup dirs
              run: |
                pwd
                mkdir -p ~/src/Hauppauge
                cd ~/src/Hauppauge
                echo "${GITHUB_WORKSPACE}"
                env

#            - name: Download Hauppauge source
#              run: |
#                mkdir -p ~/src/Hauppauge
#                cd ~/src/Hauppauge
#                curl -O https://s3.amazonaws.com/hauppauge/linux/hauppauge_hdpvr2_157321_patched_2016-09-26.tar.gz
#                tar -xzf hauppauge_hdpvr2_157321_patched_2016-09-26.tar.gz

            - name: Checkout
              uses: actions/checkout@v2
              with:
                path: src/Hauppauge/HauppaugeUSB

# pwd after checkoout: /home/runner/work/HauppaugeUSB/HauppaugeUSB
# Also GITHUB_WORKSPACE: /home/runner/work/HauppaugeUSB/HauppaugeUSB

            - name: Testing
              run: |
                cd
                pwd
                echo "----------"
                pwd
                ls -R
                echo "----------"
                cd ~/src/Hauppauge
                ls -R
                echo "----------"
