name: Release

on:
    push:
        branches:
            - action_test

# Push events to matching v*, i.e. v1.0, v20.15.10
#on:
#  push:
#    tags:
#      - 'v*'

jobs:

    compile:
        name: Compile
        runs-on: ubuntu-16.04
        steps:
            - name: Install dependancies
              run: |
                sudo apt-get install libboost-log-dev libboost-program-options-dev libusb-1.0-0-dev build-essential

            - name: Grab the "driver" from Hauppauge
              run: |
                mkdir -p ${GITHUB_WORKSPACE}/src/Hauppauge
                cd ${GITHUB_WORKSPACE}/src/Hauppauge
                curl -O https://s3.amazonaws.com/hauppauge/linux/hauppauge_hdpvr2_157321_patched_2016-09-26.tar.gz
                tar -xzf hauppauge_hdpvr2_157321_patched_2016-09-26.tar.gz

            - name: Checkout HauppaugeUSB repository
              uses: actions/checkout@v2
              with:
                path: src/Hauppauge/HauppaugeUSB

            - name: Link the Hauppauge source tree
              run: |
                cd ${GITHUB_WORKSPACE}/src/Hauppauge/HauppaugeUSB
                ln -s ../hauppauge_hdpvr2_157321_patched_2016-09-26 Hauppauge

            - name: Patch the Hauppauge source to get it working
              run: |
                cd ${GITHUB_WORKSPACE}/src/Hauppauge/HauppaugeUSB/Hauppauge
                ../HauppaugeUSB/Patches/apply_patches.sh

            - name: Rename Common/Rx/ADV7842/Wrapper.c to Wrapper.cpp so it can include c++ headers
              run: |
                cd ${GITHUB_WORKSPACE}/src/Hauppauge/HauppaugeUSB/Hauppauge
                mv Common/Rx/ADV7842/Wrapper.c Common/Rx/ADV7842/Wrapper.cpp

            - name: Build
              run: |
                cd ${GITHUB_WORKSPACE}/src/Hauppauge/HauppaugeUSB
                make
                sudo make install

            - name: Package
              run: |
                mkdir  -p ${GITHUB_WORKSPACE}/release
                cd ${GITHUB_WORKSPACE}/release
                tar cvzf HauppaugeUSB.tar.gz /opt/Hauppauge

            - name: View package
              run: |
                ls -la ${GITHUB_WORKSPACE}/release/
                ls -la ${GITHUB_WORKSPACE}/release/HauppaugeUSB.tar.gz

            - name: Show env
              run: |
                env

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                name: HauppaugeUSB.tar.gz
                path: release/HauppaugeUSB.tar.gz

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                draft: false
                prerelease: false

            - name: Upload Release Asset
              id: upload-release-asset 
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_name: HauppaugeUSB.tar.gz
                asset_path: release/HauppaugeUSB.tar.gz
                asset_content_type: application/zip
