name: Release

on:
    push:
        branches:
            - action_test

jobs:

    compile:
        name: Compile
        runs-on: ubuntu-16.04
        steps:
            - name: Install deps
              run: |
                sudo apt-get install libboost-log-dev libboost-program-options-dev libusb-1.0-0-dev build-essential

# pwd after checkoout: /home/runner/work/HauppaugeUSB/HauppaugeUSB

            - name: Testing
              run: |
                pwd
                ls
    
#            - name: Checkout
#              uses: actions/checkout@v2

