name: Release

on:
    push:
        branches:
            - action_test

jobs:

    compile:
        name: Compile
        runs-on: ubuntu-16.04
        steps:
#            - name: Install dependancies
#              run: |
#                pwd
#                sudo apt-get install libboost-log-dev libboost-program-options-dev libusb-1.0-0-dev build-essential

            - name: Grab the "driver" from Hauppauge
              run: |
                mkdir -p ${GITHUB_WORKSPACE}/src/Hauppauge
                cd ${GITHUB_WORKSPACE}/src/Hauppauge
                curl -O https://s3.amazonaws.com/hauppauge/linux/hauppauge_hdpvr2_157321_patched_2016-09-26.tar.gz
                #tar -xzf hauppauge_hdpvr2_157321_patched_2016-09-26.tar.gz

            - name: Checkout HauppaugeUSB repository
              uses: actions/checkout@v2
              with:
                path: src/Hauppauge/HauppaugeUSB

            - name: Testing
              run: |
                cd ${GITHUB_WORKSPACE}
                ls -R
